# Generated by Django 3.2.5 on 2021-07-13 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=100)),
                ('file_size', models.DecimalField(decimal_places=0, max_digits=9)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('file_content', models.TextField()),
            ],
        ),
    ]
